version: '3.1'
services:
  database:
    build:
      context: ../newsletter_back/database
      dockerfile: Dockerfile
    container_name: database
    restart: always
    volumes:
      - ../newsletter_back/database/data:/var/lib/postgres/data
    networks: 
      db:
        ipv4_address: "172.28.1.1"
    ports:
      - 5432:5432

  backend:
    build: 
      context: ../newsletter_back 
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - database
    restart: always
    networks: 
      db:
        ipv4_address: "172.28.1.2"
    ports:
      - 8080:8080
networks: 
  db:
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.0/16"
    
    